#!/usr/bin/env/python

import argparse
from astroraf.cos.ttag_funcs import lightcurve

#------------------------------------------------------------

def parse_args():
    '''
    Parse command line arguments.  Returns args object.
    '''
    parser = argparse.ArgumentParser()

    parser.add_argument('filename', type=str,  
                        help='filename of COS corrtag dataset' )

    parser.add_argument('--step', dest='step', type=int, default=5,
                        help='timestep for lightcurve')

    args = parser.parse_args()
    return args

#------------------------------------------------------------

if __name__ == "__main__":
    args = parse_args()
    lightcurve( args.filename, step=args.step, writeto=True )

